// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  main

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( SomeStruct ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SomeStruct ) UnmarshalJSON([]byte) error { return nil }
func ( SomeStruct ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SomeStruct ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SomeStruct *SomeStruct
